### PR TITLE
Filter out country version blinking in Google Terms of Services

### PR DESCRIPTION
**Pull request by LucasVerneyDGE**
Hi,

I guess this should do the trick to filter out all "country version" elements blinking in Google Terms of Services. Sadly, there is no narrow selector which could be used to filter out this text, hence I have to remove the full section of the ToS by looking at section titles.

I did not find any more robust way so far, I'm welcoming any idea on this.

Best,

### CODE REVIEW

**Comment by Ndpnt** [comment]
Hi @LucasVerneyDGE, thanks for this noise removing suggestion !

In this case, instead of creating a new filter you can use the `remove` key of the document declaration to have something similar:
```JSON
{
  "name": "Google",
  "documents": {
    …
    "Terms of Service": {
      "fetch": "https://policies.google.com/terms?hl=en-GB",
      "filter": [
        "removeUTMfromUrls"
      ],
      "select": "div[role=article]",
      "remove": [
        {
          "startBefore": "a[data-name='country-version']",
          "endBefore": "#whats-covered"
        },
        {
          "startBefore": "#footnote-country-version",
          "endBefore": "#footnote-disclaimer"
        }
      ]
    }
  }
}

```

**Comment by LucasVerneyDGE** [comment]
I missed this great addition, thanks for pointing out! This PR has been updated accordingly. Best

**Comment by LucasVerneyDGE** [comment]
By the way, in this service the removed part is known in advance (either empty or some known text). What about adding tests on these remove filter to ensure we are not removing too much information (typically, such a test could be here that we do not remove more than one `<h3>` tag)?

**Comment by Ndpnt** [comment]
> I missed this great addition, thanks for pointing out! This PR has been updated accordingly. Best
Thanks for the quick update!

Unfortunately, I'm sorry but I just saw that the modification that I asked to you won't work every time. When the country version content is not available, when the filter will try to remove it, it will throw an error. So in this specific case we cannot use the remove filter and we have to use a service filter like you did. 
But we also need to add a check in the code you wrote before to do nothing if the country specific content is not available.

I will handle the rollback and the code update.

**Comment by Ndpnt** [comment]
> By the way, in this service the removed part is known in advance (either empty or some known text). What about adding tests on these remove filter to ensure we are not removing too much information (typically, such a test could be here that we do not remove more than one `<h3>` tag)?

For know, we can add this kind of tests directly inside the filter and made it throw if we try to remove more than one `h3`.

> Also, is there a way to run the service code on a given HTML file directly (typically for easier testing of such a change)?

Not really. Currently, in the snapshot repo, I checkout to the commit corresponding to the HTML content I want to filter, and run the refilter command to check if my filter works.

**Comment by Ndpnt** [comment]
I updated the code on this branch `LucasVerneyDGE-google-country`

**Comment by Ndpnt** [comment]
Merged in #140

**Pull request closed without merging**
