### PR TITLE
Import service declarations from tosback2

### PR DESCRIPTION
**Pull request by michielbdejong**
These service declarations were imported using `scripts/tosback-import.js`.
I ran `npm run validate` and removed the declarations for which validation failed.
Issues: 
* [ ] some service names contain spaces and/or `.com` extensions. What is the common practice for choosing service names? -> https://github.com/ambanum/CGUs/issues/106
* [ ] I'll run the crawler a few times with these services and see if I get any false positives.

### CODE REVIEW

**Comment by michielbdejong** [comment]
Each time I run `npm run validate`, more services fail validation, that passed earlier. Some services that are already in master also fail intermittently.
I also need to rebuild this branch with better service names
Maybe the 95 services in https://github.com/tosdr/tosback2/tree/master/crawl_reviewed are a good first selection to focus on first.

**Comment by michielbdejong** [comment]
Imported a bunch of them with good PascalCase service name. Next steps: run `npm run validate` a few times and check if consistently passing, then `npm start` a few times and check if there are no false positives.

**Comment by michielbdejong** [comment]
I also parked some commits in the `more-documents-2` branch.

**Comment by Ndpnt** [comment]
Hi @michielbdejong,
From what I understand this PR was blocked until we defined a common practice for choosing service names. We did that in #106, so do you think this PR will be ready soon or is there still something blocking you?

**Comment by michielbdejong** [comment]
Yes, will update it tomorrow!

**Comment by michielbdejong** [comment]
Generating a new one now from a build server, using https://github.com/ambanum/TOSBack-CGUs-bridge.

**Pull request closed without merging**
